name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
    
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'gustavopaixao-dev.com'
    needs: [build, test, lint]
    steps:
      - run: echo Deploy dev
  
  deploy-qa:
    runs-on: ubuntu-latest
    environment: 
      name: qa
      url: 'gustavopaixao-qa.com'
    needs: deploy-dev
    steps:
      - run: echo Deploy qa
      
  deploy-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
      url: 'gustavopaixao-prd.com'
    needs: deploy-qa
    steps:
      - run: echo Deploy prd
